project:
  type: website
  output-dir: docs

bibliography: assets/bib/references.bib
biblio-style: apalike
link-citations: true
links-as-notes: true

website:
  title: "Tidy Intelligence"
  description: "Let your data spark joy!"
  site-url: https://blog.tidy-intelligence.com
  favicon: assets/img/favicon.ico
  search: false
  page-navigation: false
  google-analytics: 
    tracking-id: "G-YQF6MZY01S"
    storage: cookies
    anonymize-ip: true
    version: 4
  cookie-consent: 
    type: express
    style: interstitial
  navbar:
    logo-href: https://www.tidy-intelligence.com
    pinned: true
    left:
      - text: "Blog"
        file: index.qmd
      - text: "Coaching"
        url: https://www.tidy-intelligence.com/coaching.html
      - text: "Swag"
        url: https://www.etsy.com/shop/tidyswag/?etsrc=sdt&utm_source=tidy-intelligence.com

format:
  html:
    theme:
      - cosmo
      - assets/css/theme.scss
    css: 
      - assets/css/styles-global.css
      - assets/css/styles-blog.css 
    toc: false
    smooth-scroll: true
    fig-align: "center"
    fig-width: 7
    fig-height: 5
    fig-dpi: 300
    lightbox: auto
    from: markdown+emoji
