project:
  type: website
  output-dir: docs

bibliography: bib/references.bib
biblio-style: apalike
link-citations: true
links-as-notes: true

website:
  title: "Tidy Intelligence"
  description: "Let your data spark joy!"
  site-url: https://www.tidy-intelligence.com
  favicon: images/favicon.ico
  search: false
  page-navigation: false
  navbar:
    logo-href: https://www.tidy-intelligence.com
    pinned: true
    left:
      - text: "Blog"
        file: index.qmd
      - text: "About"
        url: https://www.tidy-intelligence.com/about.html

format:
  html:
    theme:
      - cosmo
      - assets/theme.scss
    css: 
      - assets/styles-global.css
      - assets/styles-blog.css
    toc: false
    smooth-scroll: true
    fig-align: "center"
    fig-width: 7
    fig-height: 5
    fig-dpi: 300
    lightbox: auto
    from: markdown+emoji

